AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Cluster, Task Definitions, and Services (including Postgres)

Parameters:
  Environment:
    Type: String
    Default: Development
    AllowedValues:
      - Development
      - Staging
      - Production
    Description: Environment name for resource tagging

  PGUser:
    Type: String
    Description: Postgres username

  PGPassword:
    Type: String
    NoEcho: true
    Description: Postgres password

Resources:
  ######################################
  # ECS Cluster
  ######################################
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${Environment}-family-photos-cluster"

  ######################################
  # Auth Task Definition
  ######################################
  AuthTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: auth-service
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !ImportValue family-photos-ExecutionRoleARN
      TaskRoleArn: !ImportValue family-photos-TaskRoleARN
      ContainerDefinitions:
        - Name: auth-service
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/auth-service:latest"
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/auth-service
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ######################################
  # Image App Task Definition
  ######################################
  ImageAppTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: image-app
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !ImportValue family-photos-ExecutionRoleARN
      TaskRoleArn: !ImportValue family-photos-TaskRoleARN
      ContainerDefinitions:
        - Name: image-app
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/image-app:latest"
          PortMappings:
            - ContainerPort: 8081
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/image-app
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  ######################################
  # Postgres Task Definition
  ######################################
  PostgresTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: postgres
      Cpu: 512
      Memory: 1024
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ContainerDefinitions:
        - Name: postgres
          Image: postgres:15
          PortMappings:
            - ContainerPort: 5432
          Environment:
            - Name: POSTGRES_USER
              Value: !Ref PGUser
            - Name: POSTGRES_PASSWORD
              Value: !Ref PGPassword
            - Name: POSTGRES_DB
              Value: auth_db
          MountPoints:
            - SourceVolume: postgres-data
              ContainerPath: /var/lib/postgresql/data
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/postgres
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
      Volumes:
        - Name: postgres-data
          EFSVolumeConfiguration:
            FilesystemId: !ImportValue family-photos-PostgresEFSId

  ######################################
  # Auth ECS Service
  ######################################
  AuthService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: auth-service
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref AuthTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - Fn::ImportValue: family-photos-preapply-PublicSubnet1
            - Fn::ImportValue: family-photos-preapply-PublicSubnet2
          SecurityGroups:
            - !ImportValue family-photos-ECSSecurityGroupId
      LoadBalancers:
        - TargetGroupArn: !ImportValue family-photos-AuthTargetGroupArn
          ContainerName: auth-service
          ContainerPort: 8080

  ######################################
  # Image App ECS Service
  ######################################
  ImageAppService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: image-app
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref ImageAppTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - Fn::ImportValue: family-photos-preapply-PublicSubnet1
            - Fn::ImportValue: family-photos-preapply-PublicSubnet2
          SecurityGroups:
            - !ImportValue family-photos-ECSSecurityGroupId
      LoadBalancers:
        - TargetGroupArn: !ImportValue family-photos-ImageAppTargetGroupArn
          ContainerName: image-app
          ContainerPort: 8081

  ######################################
  # Postgres ECS Service
  ######################################
  PostgresService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: postgres
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref PostgresTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - Fn::ImportValue: family-photos-preapply-PublicSubnet1
            - Fn::ImportValue: family-photos-preapply-PublicSubnet2
          SecurityGroups:
            - !ImportValue family-photos-ECSSecurityGroupId
      LoadBalancers: []

Outputs:
  ECSClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster