AWSTemplateFormatVersion: "2010-09-09"
Description: Pre-requisites for Family Photos projects

Resources:

  FamilyPhotosServiceGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "FamilyPhotosServiceGroup"

  FamilyUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "family_user"
      Tags:
        - Key: "Application"
          Value: "FamilyPhotosService"

  FamilyPhotosServiceGroupMembership:
    Type: "AWS::IAM::UserToGroupAddition"
    Properties:
      GroupName: "FamilyPhotosServiceGroup"
      Users:
        - !Ref FamilyUser

  GitHubActionsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "GitHubActionsPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # ECR Permissions
          - Effect: "Allow"
            Action:
              - "ecr:*"
            Resource: "*"

          # CloudFormation Permissions
          - Effect: "Allow"
            Action:
              - "cloudformation:*"
            Resource: "*"

      # Attach the Policy to the Group
      Groups:
        - !Ref FamilyPhotosServiceGroup

Outputs:
  IAMGroupName:
    Description: "Name of the IAM Group created"
    Value: !Ref FamilyPhotosServiceGroup

  IAMUserName:
    Description: "Name of the IAM User created"
    Value: !Ref FamilyUser

